export const stocks = [
  {
    symbol: 'INFY',
    name: 'Infosys',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.Gb4xi3k-tu1DaNbtFzui_wHaHa&pid=Api&P=0&h=180',
    price: 1500,
    change: '-212 (20%)',
    changeInPercent:-11,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'HDFCBANK',
    name: 'Hdfc Bank Limited',
    icon: 'https://1000logos.net/wp-content/uploads/2021/06/HDFC-Bank-logo.jpg',
    price: 1500,
    change: '-212 (20%)',
    changeInPercent:20,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ITC',
    name: 'Itc Limited',
    icon: 'https://startuptalky.com/content/images/2020/05/ITC-limited_startuptalky-min.jpg',
    price: 900,
    change: '-212 (20%)',
    changeInPercent:20,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ONGC',
    name: 'OIL & NATURAL GAS CORPORATION LIMITED',
    icon: 'https://pluspng.com/img-png/ongc-png--1102.jpg',
    price: 567,
    change: '-212 (20%)',
    changeInPercent:20,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'TITAN',
    name: 'TITAN COMPANY LIMITED',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.qNot8UYNqR_9VZa0DrxJZwHaHp&pid=Api&P=0&w=300&h=300',
    price: 345,
    change: '-212 (20%)',
    changeInPercent:-4,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ADANIENT',
    name: 'ADANI ENTERPRISES LIMITED',
    icon: 'https://tse2.mm.bing.net/th?id=OIP.IiRRKAzQShP_5HT-0h7wgAAAAA&pid=Api&P=0&h=180',
    price: 890,
    change: '-212 (20%)',
    changeInPercent:-20,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'INFY',
    name: 'Infosys',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.Gb4xi3k-tu1DaNbtFzui_wHaHa&pid=Api&P=0&h=180',
    price: 124,
    change: '-212 (20%)',
    changeInPercent:20,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'HDFCBANK',
    name: 'Hdfc Bank Limited',
    icon: 'https://1000logos.net/wp-content/uploads/2021/06/HDFC-Bank-logo.jpg',
    price: 786,
    change: '-212 (20%)',
    changeInPercent:20,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ITC',
    name: 'Itc Limited',
    icon: 'https://startuptalky.com/content/images/2020/05/ITC-limited_startuptalky-min.jpg',
    price: 84,
    change: '212 (21%)',
    changeInPercent:-9,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ONGC',
    name: 'OIL & NATURAL GAS CORPORATION LIMITED',
    icon: 'https://pluspng.com/img-png/ongc-png--1102.jpg',
    price: 672,
    change: '-212 (18%)',
    changeInPercent:-18,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'TITAN',
    name: 'TITAN COMPANY LIMITED',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.qNot8UYNqR_9VZa0DrxJZwHaHp&pid=Api&P=0&w=300&h=300',
    price: 981,
    change: '-212 (20%)',
    changeInPercent:-2,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ADANIENT',
    name: 'ADANI ENTERPRISES LIMITED',
    icon: 'https://tse2.mm.bing.net/th?id=OIP.IiRRKAzQShP_5HT-0h7wgAAAAA&pid=Api&P=0&h=180',
    price: 674,
    change: '212 (3%)',
    changeInPercent:3,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'INFY',
    name: 'Infosys',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.Gb4xi3k-tu1DaNbtFzui_wHaHa&pid=Api&P=0&h=180',
    price: 59,
    change: '212 (16%)',
    changeInPercent:16,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'HDFCBANK',
    name: 'Hdfc Bank Limited',
    icon: 'https://1000logos.net/wp-content/uploads/2021/06/HDFC-Bank-logo.jpg',
    price: 345,
    change: '-212 (14%)',
    changeInPercent:-14,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ITC',
    name: 'Itc Limited',
    icon: 'https://startuptalky.com/content/images/2020/05/ITC-limited_startuptalky-min.jpg',
    price: 981,
    change: '212 (19%)',
    changeInPercent:19,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ONGC',
    name: 'OIL & NATURAL GAS CORPORATION LIMITED',
    icon: 'https://pluspng.com/img-png/ongc-png--1102.jpg',
    price: 224,
    change: '-212 (17%)',
    changeInPercent:-17,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'TITAN',
    name: 'TITAN COMPANY LIMITED',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.qNot8UYNqR_9VZa0DrxJZwHaHp&pid=Api&P=0&w=300&h=300',
    price: 554,
    change: '212 (11%)',
    changeInPercent:11,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ADANIENT',
    name: 'ADANI ENTERPRISES LIMITED',
    icon: 'https://tse2.mm.bing.net/th?id=OIP.IiRRKAzQShP_5HT-0h7wgAAAAA&pid=Api&P=0&h=180',
    price: 557,
    change: '-212 (4%)',
    changeInPercent:4,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'INFY',
    name: 'Infosys',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.Gb4xi3k-tu1DaNbtFzui_wHaHa&pid=Api&P=0&h=180',
    price: 889,
    change: '-212 (9%)',
    changeInPercent:-9,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'HDFCBANK',
    name: 'Hdfc Bank Limited',
    icon: 'https://1000logos.net/wp-content/uploads/2021/06/HDFC-Bank-logo.jpg',
    price: 336,
    change: '-212 (20%)',
    changeInPercent:5,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ITC',
    name: 'Itc Limited',
    icon: 'https://startuptalky.com/content/images/2020/05/ITC-limited_startuptalky-min.jpg',
    price: 77,
    change: '-212 (4%)',
    changeInPercent:-4,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ONGC',
    name: 'OIL & NATURAL GAS CORPORATION LIMITED',
    icon: 'https://pluspng.com/img-png/ongc-png--1102.jpg',
    price: 24,
    change: '-212 (8%)',
    changeInPercent:-8,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'TITAN',
    name: 'TITAN COMPANY LIMITED',
    icon: 'https://tse3.mm.bing.net/th?id=OIP.qNot8UYNqR_9VZa0DrxJZwHaHp&pid=Api&P=0&w=300&h=300',
    price: 99,
    change: '-212 (5%)',
    changeInPercent:-5,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
  {
    symbol: 'ADANIENT',
    name: 'ADANI ENTERPRISES LIMITED',
    icon: 'https://tse2.mm.bing.net/th?id=OIP.IiRRKAzQShP_5HT-0h7wgAAAAA&pid=Api&P=0&h=180',
    price: 11,
    change: '-212 (20%)',
    changeInPercent:11,
    fundamentals: {
      market_cap: '93 CR',
      PE_Ratio: '55',
      PB_Ratio: '2.3',
      Industry_PE: '21.3',
      Debt_to_eq: '0.33',
      ROE: '9%',
      EPS: '9.3',
      Div_yield: '1.99%',
      Book_value: '39.3',
      Face_value: '10',
    },
  },
];

export const watchlistStocks = [
    {
      symbol: 'TITAN',
      name: 'TITAN COMPANY LIMITED',
      icon: 'https://tse3.mm.bing.net/th?id=OIP.qNot8UYNqR_9VZa0DrxJZwHaHp&pid=Api&P=0&w=300&h=300',
      price: 99,
      change: '-212 (20%)',
      fundamentals: {
        market_cap: '93 CR',
        PE_Ratio: '55',
        PB_Ratio: '2.3',
        Industry_PE: '21.3',
        Debt_to_eq: '0.33',
        ROE: '9%',
        EPS: '9.3',
        Div_yield: '1.99%',
        Book_value: '39.3',
        Face_value: '10',
      },
    },
    {
      symbol: 'ADANIENT',
      name: 'ADANI ENTERPRISES LIMITED',
      icon: 'https://tse2.mm.bing.net/th?id=OIP.IiRRKAzQShP_5HT-0h7wgAAAAA&pid=Api&P=0&h=180',
      price: 11,
      change: '-212 (20%)',
      fundamentals: {
        market_cap: '93 CR',
        PE_Ratio: '55',
        PB_Ratio: '2.3',
        Industry_PE: '21.3',
        Debt_to_eq: '0.33',
        ROE: '9%',
        EPS: '9.3',
        Div_yield: '1.99%',
        Book_value: '39.3',
        Face_value: '10',
      },
    },
  ];
  